language: ruby

services:
  - docker

env:
  - REDMINE=3.3
  - REDMINE=3.4
  - REDMINE=4.0
  - REDMINE=4.1

matrix:
  fast_finish: true

before_install:
  - cd test
  - docker-compose pull
  - docker-compose build

script:
  - ./start.sh
